## 本配置文件定义了车辆的各方面的属性和功能函数。
ID: car
version: 0.0.1
auth: admin
desc: 智能汽车
# 固定属性
invariant-attr:
  -
    key: model
    name: 型号
    data-type: string
    required: false
    default-value:
    unit:
  -
    key: brand
    name: 品牌
    data-type: string
    required: false
    default-value:
    unit:
  -
    key: engine
    name: 发动机ID
    data-type: string
    required: true
    default-value:
    unit:
  -
    key: tank_capacity
    name: 油箱容量
    data-type: int16
    required: false
    default-value: 40
    unit: L
  -
    key: licence_plate
    name: 车牌号码
    data-type: string
    required: true
    default-value:
    unit:

# 传感属性定义

read-attr:
  -
    key: driving_speed
    name: 行驶速度
    data-type: int16
    default-value:
    unit: km/h
  -
    key: remaining_battery_life
    name: 剩余续航里程
    data-type: int16
    default-value:
    unit: km
  -
    key: driving_state
    name: 行驶状态
    data-type: bool
    default-value:
    unit:
  -
    key: latitude
    name: 经度
    data-type: float64
    required: true
    default-value:
    unit:
  -
    key: longitude
    name: 纬度
    data-type: float64
    required: true
    default-value:
    unit:

# 配置属性定义

config-attr:
  -
    key: lock_state
    name: 锁状态
    data-type: bool
    default-value:
    unit:
  -
    key: monitoring_mode
    name: 监控模式
    data-type: bool
    default-value:
    unit:


## 事件定义

event:
  -
    key: crash_event
    name: 碰撞事件
    level: 2 # [0:通知]、[1:异常]、[2:故障]
    out-params:
      -
        key: latitude
        name: 经度
        data-type: float64
        default-value:
      -
        key: longitude
        name: 纬度
        data-type: float64
        default-value:

## 功能函数

function:
  -
    key: automatic_driving
    name: 自动驾驶
    in-params:
      -
        key: latitude
        name: 经度
        data-type: float64
        required: true
        default-value:
      -
        key: longitude
        name: 纬度
        data-type: float64
        required: true
        default-value: