host: localhost:10010"
info:
  contact:
    email: jin-chunguang@foxmail.com
    name: jinchunguang
  description: 给予gin web框架搭建的业务骨架
  license: {}
  termsOfService: http://swagger.io/terms/
  title: gin 框架
  version: "1.0"
paths:
  /user/{id}:
    get:
      consumes:
      - application/x-json-stream
      description: 通过id获取用户
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
swagger: "2.0"
